routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AlunosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\DisciplinasController;
use App\Http\Controllers\MatriculasController;
use App\Http\Controllers\FuncionariosController;
use App\Http\Controllers\CargosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function () {
    return view('hello');
});

Route::get('/alunos', [AlunosController::class, 'index']);
// Route::get('/disciplinas', [DisciplinasController::class, 'index']);

Route::resource('cursos', CursosController::class);

Route::resource('students', StudentsController::class);

// Aula relacionamentos de tabelas
Route::get('/relatorios/listadisciplinascurso', [CursosController::class, 'listaDisciplinasCurso']);

Route::resource('disciplinas', DisciplinasController::class);
Route::resource('matriculas', MatriculasController::class);


// Exercícios
Route::resource('funcionarios', FuncionariosController::class);
Route::resource('cargos', CargosController::class);

app/Models/Cargos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Funcionarios;

class Cargos extends Model
{
    protected $table = 'cargos';
    protected $fillable = ['name', 'description'];

    public function funcionarios() {
        return $this->hasMany(Funcionarios::class, 'cargos_id'); 
    }

    use HasFactory;
}

app/Http/Controllers/CargosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cargos;
use App\Models\Funcionarios;
use Illuminate\Http\Request;

class CargosController extends Controller
{
    public function index()
    {
        $cargos = Cargos::all();
        return view('cargos/index', compact('cargos'));
    }

    public function create()
    {
        return view('cargos/cadastrar');
    }

    public function store(Request $request)
    {
        Cargos::create($request->all());
        return redirect('cargos');
    }

    public function show($id)
    {
        $funcionarios = Funcionarios::all()->where("cargos_id", "=", $id);
        return view('cargos/funcionarios', compact('funcionarios'));
    }

    public function edit($id)
    {
        $cargos = Cargos::find($id);
        return view('cargos/edit', compact('cargos'));
    }

    public function update(Request $request, $id)
    {
        $cargos = Cargos::find($id);
        echo($cargos);
        $cargos->update($request->all());
        return redirect('cargos');
    }

    public function destroy($id)
    {
        $cargos = Cargos::find($id);
        echo($cargos);
        $cargos->delete();
        return redirect('cargos');
    }
}

resources/views/cargos/cadastrar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Cadastrar cargos</h1>
  <form action="{{route('cargos.store')}}" method="POST">
    @csrf
    <br>
    <label>Nome</label>
    <input type="text" name="name"  />

    <label>Descrição</label>
    <input type="text" name="description"  />
    <button type="submit">Enviar</button>
  </form>
</body>
</html>

resources/views/cargos/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Editar Funcionario</title>
</head>
<style>
body {
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    width: 100%;
}
form {
  display: flex;
  flex-flow: column;
  justify-content: center;
  align-items: center;
  width: 20rem;
}
form div {
  display: flex;
  justify-content: space-evenly;
  width: 100%;
  align-items: center;
}
form div textarea {
  width: 87%;
  padding: 0.3rem 1rem;
}
form div input, textarea {
  margin: 1rem;
}
form button {
  padding: .7rem 2rem;
  margin-top: 2rem;
  cursor: pointer;
}
form div input {
  padding: .7rem 1rem;
}

</style>
<body>
  <h1>Editar Cargo</h1>
  <form action="{{ route('cargos.update', $cargos->id) }}" method="POST">
    @csrf
    @method('PUT')
    <label>Nome</label>
    <input type="text" name="name" value="{{ $cargos->name }}"   />
    <label>Descrição</label>
    <input type="text" name="description" value="{{ $cargos->description }}"  />
    <button type="submit">Atualizar</button>
  </form>
</body>
</html>

resources/views/cargos/funcionarios.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<h1>Funcionarios</h1>
  <section>
      <table border="1">
        <tr>
          <th>Nome</th>
          <th>CPF</th>
          <th>Email</th>
          <th>Salário Base</th>
          <th>Ano de Admissão</th>
          <th>Cargo</th>
        </tr>
        @foreach ($funcionarios as $funcionarios)
        <tr>
          <td style="padding: .4rem">{{ $funcionarios->nome }}</td>
          <td style="padding: .4rem">{{ $funcionarios->cpf }}</td>
          <td style="padding: .4rem">{{ $funcionarios->email }}</td>
          <td style="padding: .4rem">{{ $funcionarios->salario_base }}</td>
          <td style="padding: .4rem">{{ $funcionarios->ano_admissao }}</td>
          <td style="padding: .4rem">{{ $funcionarios->cargos->name }}</td>
        @endforeach
        </tr>
      </table>
  </section>
</body>
</html>

resources/views/cargos/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cargos</title>
</head>
<body>
  <h1>Cadastrar cargos</h1>
  <a href="{{url('cargos/create')}}">Adicionar Cargo</a>

  <h1>Cargos</h1>
  @foreach($cargos as $cargo)
  <form action="{{route('cargos.show', $cargo->id)}}" method="GET">
    @csrf
    @method('GET')
    <span name="cargos_id">{{ $cargo->name ?? '' }}</span>
    <button type="submit">Funcionários</button>
  </form>
  @endforeach
  <table border="1">
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Editar</th>
      <th>Deletar</th>
    </tr>
    @foreach ($cargos as $cargo)
    <tr>
      <td style="padding: .4rem">{{ $cargo->name }}</td>
      <td style="padding: .4rem">{{ $cargo->description }}</td>
      <td style="padding: .4rem">
        <a href="{{url('cargos/'.$cargo->id.'/edit')}}">
          <button>Editar</button>
        </a>
      </td>
      <td style="padding: .4rem"> 
        <form action="{{ route('cargos.destroy',$cargo->id) }}" method="POST">
          @csrf
          @method('DELETE')
          <button type="submit">Deletar</button>
        </form>
      </td>
    @endforeach
    </tr>
  </table>
</body>
</html>