routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AlunosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\DisciplinasController;
use App\Http\Controllers\MatriculasController;
use App\Http\Controllers\FuncionariosController;
use App\Http\Controllers\CargosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function () {
    return view('hello');
});

Route::get('/alunos', [AlunosController::class, 'index']);
// Route::get('/disciplinas', [DisciplinasController::class, 'index']);

Route::resource('cursos', CursosController::class);

Route::resource('students', StudentsController::class);

// Aula relacionamentos de tabelas
Route::get('/relatorios/listadisciplinascurso', [CursosController::class, 'listaDisciplinasCurso']);

Route::resource('disciplinas', DisciplinasController::class);
Route::resource('matriculas', MatriculasController::class);


// Exercícios
Route::resource('funcionarios', FuncionariosController::class);
Route::resource('cargos', CargosController::class);

app/Models/Cursos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Disciplinas;

class Cursos extends Model
{
    protected $table = 'cursos';
    public $fillable = ['nome', 'descricao'];
    use HasFactory;

    // Buscar as disciplinas que pertencem a esse cursos
    // Um para muitos
    public function disciplinas_curso() {
        return $this->hasMany(Disciplinas::class);
    }
}

app/Http/Controllers/CursosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cursos;

class CursosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cursos = Cursos::all();
        return view('cursos/index', compact('cursos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // chama o formulário para cadastro
        return view('cursos/cadastrar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $rules = [
            'nome' => 'required | min:5 | max:100',
            'descricao' => 'required',
        ];

        $params = [
            'required' => 'O preenchimento do campo :attribute é obrigatório',
            'max' => 'O campo :attribute possui tamanho máximo de :max caracteres',
            'min' => 'O campo :attribute possui tamanho máximo de :min caracteres'
        ];

        $request->validate($rules, $params);

        // cadastra o curso no db -> fillable
        Cursos::create($request->all());
        // redirect page
        return redirect('cursos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cursos = Cursos::find($id);
        return view('cursos/editar', compact('cursos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // buscar o registro a ser alterado
        $cursos = Cursos::find($id);
        $cursos->update($request->all());
        return redirect('cursos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // excluir do db
        $cursos = Cursos::find($id);
        $cursos->delete();
        return redirect('cursos');
    }
    
    public function listaDisciplinasCurso(Request $request) {
        $cursos = Cursos::all();
        $cursoEscolhido = Cursos::find($request->id);
        if(isset($cursoEscolhido->disciplinas_curso)){
            $disciplinas_curso = $cursoEscolhido->disciplinas_curso;
        } else {
            $disciplinas_curso = null;
        }

        return view('relatorios/listaDisciplinasCurso', compact('cursos', 'disciplinas_curso'));
    }
}

resources/views/cursos/cadastrar.blade.php
@extends('layout.main')

@section('title')
  Cadastrar cursos
@endsection

@section('content')
  <form action="{{route('cursos.store')}}" method="POST">
    @csrf
    <br>
    <label>Nome do curso</label>
    <input type="text" name="nome" value="{{ old('nome') }}"  />

    <label>Descricao do curso</label>
    <input type="text" name="descricao" value="{{ old('descricao') }}" />

    <button type="submit">Enviar</button>
  </form>
  <br>
  @if ($errors->any())
    <div class="alert, alert-danger p-2">
      <strong>Não foi possível realizar cadastro, devido aos seguintes erros:</stro>
      <ul>
        @foreach ($errors->all() as $erro)
          <li>{{ $erro }}</li>
        @endforeach
      </ul>
    </div>
  @endif
@endsection

resources/views/cursos/editar.blade.php
@extends('layout.main')

@section('title')
  Cadastrar cursos
@endsection

@section('content')
  <form action="{{route('cursos.update', $cursos->id)}}" method="POST">
    @csrf
    @method('PUT')
    <br>
    <label>Nome do curso</label>
    <input type="text" name="nome" value="{{$cursos->nome}}" />

    <label>Descricao do curso</label>
    <input type="text" name="descricao" value="{{$cursos->descricao}}" />

    <button type="submit">Alterar</button>
  </form>
@endsection

resources/views/cursos/index.blade.php
@extends('layout.main')

@section('title')
  Cursos Cadastrados
@endsection

@section('content')
  <a class="pt-2 d-block" href="{{url('cursos/create')}}">Adicionar curso</a>
  <br>
  @foreach($cursos as $curso)
    <hr class="mt-5 mb-5 d-block">
    <h3 >Nome: {{ $curso->nome }}</h3>
    <span>Id: {{ $curso->id }} </span>
    <p>Descrição: {{ $curso->descricao }}</p>
    <a class="d-block pt-2 pb-2" href="{{url('cursos/'.$curso->id.'/edit')}}">
      <button class="p-1 pl-3 pr-3 border-0 outline-0 bg-primary text-light">Editar</button>
    </a>
    <form action="{{ route('cursos.destroy',$curso->id) }}" method="POST">
      @csrf
      @method('DELETE')
      <button class="p-1 pl-3 pr-3 border-0 outline-0 bg-danger text-light" type="submit">Excluir</button>
    </form>
  @endforeach
@endsection