routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AlunosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\DisciplinasController;
use App\Http\Controllers\MatriculasController;
use App\Http\Controllers\FuncionariosController;
use App\Http\Controllers\CargosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function () {
    return view('hello');
});

Route::get('/alunos', [AlunosController::class, 'index']);
// Route::get('/disciplinas', [DisciplinasController::class, 'index']);

Route::resource('cursos', CursosController::class);

Route::resource('students', StudentsController::class);

// Aula relacionamentos de tabelas
Route::get('/relatorios/listadisciplinascurso', [CursosController::class, 'listaDisciplinasCurso']);

Route::resource('disciplinas', DisciplinasController::class);
Route::resource('matriculas', MatriculasController::class);


// Exercícios
Route::resource('funcionarios', FuncionariosController::class);
Route::resource('cargos', CargosController::class);

app/Models/Students.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Students extends Model
{
    protected $table = 'alunos';
    public $fillable = ['name', 'email', 'address', 'phone', 'cpf'];
    use HasFactory;
}

app/Http/Controllers/StudentsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Students;
use Illuminate\Http\Request;

class StudentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Students::all();
        return view('students/index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students/register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Students::create($request->all());
        return redirect('students');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Students::find($id);
        return view('students/edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student = Students::find($id);
        $student->update($request->all());
        return redirect('students');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $students = Students::find($id);
        $students->delete();
        return redirect('students');
    }
}

resources/views/students/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Editar Estudante</title>
</head>
<style>
body {
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    width: 100%;
}
form {
  display: flex;
  flex-flow: column;
  justify-content: center;
  align-items: center;
  width: 20rem;
}
form div {
  display: flex;
  justify-content: space-evenly;
  width: 100%;
  align-items: center;
}
form div textarea {
  width: 87%;
  padding: 0.3rem 1rem;
}
form div input, textarea {
  margin: 1rem;
}
form button {
  padding: .7rem 2rem;
  margin-top: 2rem;
  cursor: pointer;
}
form div input {
  padding: .7rem 1rem;
}

</style>
<body>
  <h1>Editar Estudante</h1>
  <form action="{{ route('students.update', $student->id) }}" method="POST">
    @csrf
    @method('PUT')
    <div>
      <label>Nome do Estudante</label>
      <input name="name" type="text" value="{{ $student->name }}"  />
    </div>

    <div>
      <label>Email do Estudante</label>
      <input name="email" type="email" value="{{ $student->email }}"  />
    </div>

    <div>
      <label>Endereço do Estudante</label>
      <textarea name="address" type="text">{{ $student->address }}</textarea>
    </div>

    <div>
      <label>Telefone do Estudante</label>
      <input name="phone" type="number" value="{{ $student->phone }}"  />
    </div>

    <div>
      <label>CPF do Estudante</label>
      <input name="cpf" type="text" value="{{ $student->cpf }}" />
    </div>

    <button type="submit">Atualizar</button>
  </form>
</body>
</html>

resources/views/students/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Students</title>
</head>
<style>
  main {
    display: flex;
    flex-flow: column;
    width: 100%;
    min-height: 100vh;
    align-items: center;
    justify-content: center;
  }
</style>
<body>
  <main>
  <h2>Students</h2>
    <a href="{{url('students/create')}}">Adicionar Estudante</a>
    <section>
      
      <table border="1">
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Endereço</th>
          <th>Telefone</th>
          <th>CPF</th>
          <th>Editar</th>
          <th>Deletar</th>
        </tr>
        @foreach ($students as $student)
        <tr>
          <td style="padding: .4rem">{{ $student->name }}</td>
          <td style="padding: .4rem">{{ $student->email }}</td>
          <td style="padding: .4rem">{{ $student->address }}</td>
          <td style="padding: .4rem">{{ $student->phone }}</td>
          <td style="padding: .4rem">{{ $student->cpf }}</td>
          <td style="padding: .4rem">
            <a href="{{url('students/'.$student->id.'/edit')}}">
              <button>Editar</button>
            </a>
          </td>
          <td style="padding: .4rem"> 
            <form action="{{ route('students.destroy',$student->id) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit">Deletar</button>
            </form>
          </td>

        @endforeach
        </tr>
      </table>
    </section>
  </main>
</body>
</html>

resources/views/students/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastrar Estudante</title>
</head>
<style>
  body {
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    width: 100%;
  }
  form {
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    width: 20rem;
  }
  form div {
    display: flex;
    justify-content: space-evenly;
    width: 100%;
    align-items: center;
  }
  form div textarea {
    width: 87%;
    padding: 0.3rem 1rem;
  }
  form div input, textarea {
    margin: 1rem;
  }
  form button {
    padding: .7rem 2rem;
    margin-top: 2rem;
    cursor: pointer;
  }
  form div input {
    padding: .7rem 1rem;
  }
</style>
<body>
  <h1>Cadastrar Estudante</h1>
  <form action="{{route('students.store')}}" method="POST">
    @csrf
    <div>
      <label>Nome do Estudante</label>
      <input name="name" type="text"  />
    </div>

    <div>
      <label>Email do Estudante</label>
      <input name="email" type="email"  />
    </div>

    <div>
      <label>Endereço do Estudante</label>
      <textarea name="address" type="text"></textarea>
    </div>

    <div>
      <label>Telefone do Estudante</label>
      <input name="phone" type="number"  />
    </div>

    <div>
      <label>CPF do Estudante</label>
      <input name="cpf" type="text"  />
    </div>
    
    <button type="submit">Cadastrar</button>
  </form>
</body>
</html>