routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AlunosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\DisciplinasController;
use App\Http\Controllers\MatriculasController;
use App\Http\Controllers\FuncionariosController;
use App\Http\Controllers\CargosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/hello', function () {
    return view('hello');
});

Route::get('/alunos', [AlunosController::class, 'index']);
// Route::get('/disciplinas', [DisciplinasController::class, 'index']);

Route::resource('cursos', CursosController::class);

Route::resource('students', StudentsController::class);

// Aula relacionamentos de tabelas
Route::get('/relatorios/listadisciplinascurso', [CursosController::class, 'listaDisciplinasCurso']);

Route::resource('disciplinas', DisciplinasController::class);
Route::resource('matriculas', MatriculasController::class);


// Exercícios
Route::resource('funcionarios', FuncionariosController::class);
Route::resource('cargos', CargosController::class);

app/Models/Funcionarios.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Cargos;

class Funcionarios extends Model
{
    protected $table = 'funcionarios';
    public $fillable = ['id', 'nome', 'cpf', 'email', 'salario_base', 'ano_admissao', 'cargos_id'];
    use HasFactory;

    public function cargos() {
        return $this->belongsTo(Cargos::class);
    }
}

app/Http/Controllers/FuncionariosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cargos;
use App\Models\Funcionarios;
use Illuminate\Http\Request;

class FuncionariosController extends Controller
{

    public function index()
    {
        $funcionarios = Funcionarios::all();
        return view('funcionarios/index', compact('funcionarios'));
    }

    public function create()
    {
        $cargos = Cargos::all();
        return view('funcionarios/register', compact('cargos'));
    }

    public function store(Request $request)
    {
        Funcionarios::create($request->all());
        return redirect('funcionarios');
    }

    public function show(Funcionarios $funcionarios)
    {

    }

    public function edit($id)
    {
        $funcionarios = Funcionarios::find($id);
        $cargos = Cargos::all();
        return view('funcionarios/edit', compact('funcionarios', 'cargos'));
    }

    public function update(Request $request, $id)
    {
        $funcionarios = Funcionarios::find($id);
        $funcionarios->update($request->all());
        return redirect('funcionarios');
    }

    public function destroy($id)
    {
        $funcionarios = Funcionarios::find($id);
        $funcionarios->delete();
        return redirect('funcionarios');
    }
}

resources/views/funcionarios/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Editar Funcionario</title>
</head>
<style>
body {
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    width: 100%;
}
form {
  display: flex;
  flex-flow: column;
  justify-content: center;
  align-items: center;
  width: 20rem;
}
form div {
  display: flex;
  justify-content: space-evenly;
  width: 100%;
  align-items: center;
}
form div textarea {
  width: 87%;
  padding: 0.3rem 1rem;
}
form div input, textarea {
  margin: 1rem;
}
form button {
  padding: .7rem 2rem;
  margin-top: 2rem;
  cursor: pointer;
}
form div input {
  padding: .7rem 1rem;
}

</style>
<body>
  <h1>Editar Funcionário {{ $funcionarios->id }}</h1>
  <form action="{{ route('funcionarios.update', $funcionarios->id) }}" method="POST">
    @csrf
    @method('PUT')
    <br>
    <label>Nome</label>
    <input type="text" name="nome" value="{{ $funcionarios->nome }}"  />

    <label>CPF</label>
    <input type="text" name="cpf" value="{{ $funcionarios->cpf }}" />

    <label>Email</label>
    <input type="text" name="email" value="{{ $funcionarios->email }}" />

    <label>Salário base</label>
    <input type="text" name="salario_base" value="{{ $funcionarios->salario_base }}" />

    <label>Ano de admissão</label>
    <input type="text" name="ano_admissao" value="{{ $funcionarios->ano_admissao }}" />

    <label>Cargos</label>
    <select name="cargos_id" id="cargos_id">
      @foreach ($cargos as $cargos)
          <option name="cargos_id" value="{{ $cargos->id }}">{{ $cargos->name }}</option>
      @endforeach
    </select>
    <button type="submit">Atualizar</button>
  </form>
</body>
</html>

resources/views/funcionarios/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Funcionarios</title>
</head>
<style>
  main {
    display: flex;
    flex-flow: column;
    width: 100%;
    min-height: 100vh;
    align-items: center;
    justify-content: center;
  }
</style>
<body>
  <main>
  <h2>Funcionarios</h2>
    <a href="{{url('funcionarios/create')}}">Adicionar Funcionario</a>
    <section>
      <table border="1">
        <tr>
          <th>Nome</th>
          <th>CPF</th>
          <th>Email</th>
          <th>Salário Base</th>
          <th>Ano de Admissão</th>
          <th>Cargo</th>
          <th>Editar</th>
          <th>Deletar</th>
        </tr>
        @foreach ($funcionarios as $funcionarios)
        <tr>
          <td style="padding: .4rem">{{ $funcionarios->nome }}</td>
          <td style="padding: .4rem">{{ $funcionarios->cpf }}</td>
          <td style="padding: .4rem">{{ $funcionarios->email }}</td>
          <td style="padding: .4rem">{{ $funcionarios->salario_base }}</td>
          <td style="padding: .4rem">{{ $funcionarios->ano_admissao }}</td>
          <td style="padding: .4rem">{{ $funcionarios->cargos->name }}</td>
          <td style="padding: .4rem">
            <a href="{{url('funcionarios/'.$funcionarios->id.'/edit')}}">
              <button>Editar</button>
            </a>
          </td>
          <td style="padding: .4rem"> 
            <form action="{{ route('funcionarios.destroy',$funcionarios->id) }}" method="POST">
              @csrf
              @method('DELETE')
              <button type="submit">Deletar</button>
            </form>
          </td>
        @endforeach
        </tr>
      </table>
    </section>
  </main>
</body>
</html>

resources/views/funcionarios/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cadastrar Funcionario</title>
</head>
<style>
  body {
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    width: 100%;
  }
  form {
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    width: 20rem;
  }
  form div {
    display: flex;
    justify-content: space-evenly;
    width: 100%;
    align-items: center;
  }
  form div textarea {
    width: 87%;
    padding: 0.3rem 1rem;
  }
  form div input, textarea {
    margin: 1rem;
  }
  form button {
    padding: .7rem 2rem;
    margin-top: 2rem;
    cursor: pointer;
  }
  form div input {
    padding: .7rem 1rem;
  }
</style>
<body>
  <h1>Cadastrar Funcionario</h1>
  <form action="{{route('funcionarios.store')}}" method="POST">
    @csrf
    <br>
    <label>Nome</label>
    <input type="text" name="nome"  />

    <label>CPF</label>
    <input type="text" name="cpf"  />

    <label>Email</label>
    <input type="text" name="email"  />

    <label>Salário base</label>
    <input type="text" name="salario_base"  />

    <label>Ano de admissão</label>
    <input type="text" name="ano_admissao"  />

    <label>Cargos</label>
    <select name="cargos_id" id="cargos_id">
      @foreach ($cargos as $cargos)
          <option name="cargos_id" value="{{ $cargos->id }}">{{ $cargos->name }}</option>
      @endforeach
    </select>
    <button type="submit">Enviar</button>
  </form>
</body>
</html>